fitness_gym/main/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('contacts/feedback', views.feedback, name='feedback'),
]

fitness_gym/news/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.NewsList.as_view(), name='news'),
    path('category/<int:category_id>/', views.NewsByCategory.as_view(), name='category'),
    path('<int:pk>/', views.ViewNews.as_view(), name='view_news'),
    path('comment/add/', views.add_comment, name='add-comment'),
]

fitness_gym/news/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    title = models.CharField(verbose_name='Название', max_length=50, db_index=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('category', kwargs={'category_id': self.pk})


class News(models.Model):
    title = models.CharField(verbose_name='Наименование', max_length=75)
    content = models.TextField(verbose_name='Контент', blank=True)
    photo = models.ImageField(verbose_name='Фото', upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(verbose_name='Опубликовано', default=True)
    category = models.ForeignKey(verbose_name='Категория', to='Category', on_delete=models.PROTECT, null=True)
    views = models.IntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.PROTECT, default=1)
    created_at = models.DateTimeField(verbose_name='Дата публикации', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Обнавлено', auto_now=True)

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['-created_at', 'title']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('view_news', kwargs={'pk': self.pk})


class NewsComment(models.Model):
    news = models.ForeignKey(News, on_delete=models.PROTECT, default=1)
    user = models.ForeignKey(User, on_delete=models.PROTECT, default=1)
    text = models.TextField()
    created_at = models.DateTimeField(verbose_name='Дата публикации', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='Обнавлено', auto_now=True)

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.news} | {self.user}"

fitness_gym/news/forms.py
from django import forms
from .models import NewsComment
from ckeditor_uploader.widgets import CKEditorUploadingWidget
from ckeditor_uploader.fields import RichTextUploadingField


class NewsCommentForm(forms.ModelForm):
    text = forms.CharField(widget=CKEditorUploadingWidget())

    class Meta:
        model = NewsComment
        fields = ['text', 'user', 'news']
        widgets = {
            'user': forms.HiddenInput(),
            'news': forms.HiddenInput(),
        }

fitness_gym/news/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from .models import News, Category, NewsComment
from django.views.generic import ListView, DetailView
from .forms import NewsCommentForm
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import F


class NewsList(ListView):
    model = News
    context_object_name = 'news'
    paginate_by = 2
    template_name = 'news/blog.html'

    def get_queryset(self):
        return News.objects.filter(is_published=True).select_related('category')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'News'
        context['sub_title'] = 'All'
        return context


class NewsByCategory(ListView):
    model = News
    context_object_name = 'news'
    allow_empty = False
    paginate_by = 2
    template_name = 'news/blog.html'

    def get_queryset(self):
        return News.objects.filter(category_id=self.kwargs['category_id'], is_published=True).select_related('category')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "News"
        context['sub_title'] = Category.objects.get(pk=self.kwargs['category_id']).title
        return context


class ViewNews(DetailView):
    model = News
    context_object_name = 'news_item'
    template_name = 'news/view_news.html'
    comment_form = NewsCommentForm
    comment_on_page = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "News"
        context['sub_title'] = News.objects.get(pk=self.kwargs['pk']).title
        context['comment_total'] = int(NewsComment.objects.filter(news=self.kwargs['pk']).count())
        context['comment_form'] = self.comment_form

        paginator = Paginator(NewsComment.objects.filter(news=self.kwargs['pk']), self.comment_on_page)
        page_number = self.request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj

        self.object.views += 1
        self.object.save()
        return context


def add_comment(request):
    if request.method == 'POST':
        form = NewsCommentForm(request.POST)
        if form.is_valid():
            form.cleaned_data['user'] = request.user.pk
            form.cleaned_data['news'] = form.cleaned_data['news'].pk
            form.save()
            messages.success(request, 'Комментарий был опубликован')
            return HttpResponseRedirect(request.META.get('HTTP_REFERER', 'home'))
        else:
            messages.error(request, 'Ошибка публикации комментария :(')

fitness_gym/news/templates/news/blog.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- ##### Blog Area Start ##### -->
<div class="blog-area mt-50 section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <div class="fitness-blog-posts">
                    <div class="row">

                        {% for item in news%}
                        <!-- Single Blog Start -->
                        <div class="col-12">
                            <div class="single-blog-post mb-100">
                                <!-- Post Thumb -->
                                <div class="blog-post-thumb mb-30">
                                    {% if item.photo %}
                                    <img src="{{ item.photo.url }}" alt="">
                                    {% else %}
                                    <img src="{% static 'img/blog-img/1.png' %}" alt="">
                                    {% endif %}
                                    <div class="post-date">
                                        <p><span>{{ item.created_at|date:"M" }}</span>{{ item.created_at|date:"d" }}</p>
                                    </div>
                                </div>
                                <!-- Post Title -->
                                <a href="{% url 'view_news' item.pk %}" class="post-title">{{item.title}}</a>
                                <!-- Post Meta -->
                                <div class="post-meta">
                                    <p>By <a href="#">{{ item.author.first_name }}</a>
                                        | in <a href="{% url 'category' item.category.pk %}">{{ item.category.title }}</a>
                                        | <a href="{% url 'view_news' item.pk %}#comments">{{ item.newscomment_set.all.count }} comments</a>
                                        | {{ item.views }} views
                                    </p>
                                </div>
                                <!-- Post Excerpt -->
                                <p>{{ item.content | safe | truncatewords:50 }}</p>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                {% block pagination %}
                {% include 'inc/_pagination.html' %}
                {% endblock %}
            </div>

            <div class="col-12 col-md-4">
                <div class="fitness-blog-sidebar">

                    <!-- Add Widget -->
                    <div class="add-widget mb-100">
                        <a href="#"><img src="{% static 'img/bg-img/add3.png' %}" alt=""></a>
                    </div>

                    <!-- Blog Post Catagories -->
                    {% load news_tags %}
                    {% show_categories %}

                </div>
            </div>
        </div>
    </div>
</div>
<!-- ##### Blog Area End ##### -->
{% endblock %}

fitness_gym/news/templates/news/list_categories.html
<div class="blog-post-categories mb-100">
    <h5>Categories</h5>
    <ul>
        <li><a href="{% url 'news' %}">
            <span>Все</span>
            <span class="badge badge-pill badge-primary">{{ total_news }}</span>
        </a></li>

        {% for c in categories %}
        <li><a href="{% url 'category' c.pk %}">
            <span>{{ c.title }}</span>
            <span class="badge badge-pill badge-success">{{c.cnt}}</span>
        </a></li>
        {% endfor %}
    </ul>
</div>

fitness_gym/news/templates/news/view_news.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
| {{ news_item.title }}
{% endblock %}

{% block content %}
<div class="blog-area mt-50 section-padding-100">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-8">
                <div class="fitness-blog-posts">
                    <div class="row">

                        <!-- Single Blog Start -->
                        <div class="col-12">
                            <div class="single-blog-post mb-100">
                                <!-- Post Thumb -->
                                <div class="blog-post-thumb mb-30">
                                    {% if news_item.photo %}
                                    <img src="{{ news_item.photo.url }}" alt="">
                                    {% else %}
                                    <img src="{% static 'img/blog-img/1.png' %}" alt="">
                                    {% endif %}
                                </div>
                                <!-- Post Title -->
                                <a href="#" class="post-title">{{news_item.title}}</a>
                                <!-- Post Meta -->
                                <div class="post-meta">
                                    <p>By <a href="#">{{ news_item.author.first_name }}</a>
                                        | in <a href="#">{{ news_item.category.title }}</a>
                                        | <a href="#comments">{{comment_total}} comments</a>
                                        | at {{ news_item.created_at|date:"d-m-Y" }}
                                        | {{ news_item.views }} views
                                    </p>
                                </div>
                                <!-- Post Excerpt -->
                                <p>{{ news_item.content | safe}}</p>
                            </div>
                        </div>
                        <!-- Single Blog End -->

                    </div>
                </div>

                {% include 'inc/_commentaries.html' %}

            </div>

            <div class="col-12 col-md-4">
                <div class="fitness-blog-sidebar">
                    <!-- Blog Post Catagories -->
                    {% load news_tags %}
                    {% show_categories %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}